// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Helper: strip surrounding quotes (some .env editors include them)
function stripQuotes(v: unknown) {
  if (typeof v !== 'string') return v;
  return v.replace(/^"(.*)"$/, '$1').trim();
}

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = stripQuotes(rawUrl) as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = stripQuotes(rawKey) as string | undefined;

if (import.meta.env.DEV) {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Helpful, actionable message for local dev
    // eslint-disable-next-line no-console
    console.error(
      'Supabase env vars missing: ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in .env and that you restarted the dev server.'
    );
  } else {
    try {
      const url = new URL(SUPABASE_URL);
      if (!url.protocol.startsWith('http')) {
        // eslint-disable-next-line no-console
        console.warn('VITE_SUPABASE_URL does not look like a valid HTTP URL:', SUPABASE_URL);
      }
    } catch (e) {
      // eslint-disable-next-line no-console
      console.warn('VITE_SUPABASE_URL is not a valid URL:', SUPABASE_URL);
    }
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL ?? '', SUPABASE_PUBLISHABLE_KEY ?? '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});